### PR TITLE
Update microkit dep & enable debug server

### PR DESCRIPTION
**Pull request by tuommaki**
Added debug server exposes net/http/pprof interface in
http://127.0.0.1:6060/debug.

This helps with profiling running service e.g. when it's OOMing.

Towards https://github.com/giantswarm/giantswarm/issues/4088

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Comment by xh3b4sd** [comment]
Can we merge this?

**Comment by xh3b4sd** [comment]
Hello.

**Comment by MarcelMue** [comment]
I already gave approval, who are you asking?

**Comment by xh3b4sd** [comment]
The PR is approved since 12 days so I just want to have a communication and want to know why this is still not merged and if we can do it.

**Pull request merged**
